=== GNOME/libgda/tests/db/libgda-ddl-creator.dtd
<!--      libgda-ddl-creator.dtd
          DTD for libgda's ddl objects
          Version 1.0
          Copyright (C) 2018 Pavlo Solntsev
-->

<!ELEMENT schema (table+, view*)>
<!ATTLIST schema name ID #REQUIRED>

<!ELEMENT table (comment?,column+, fkey*)>
<!ATTLIST table temptable	(TRUE|FALSE)	"FALSE">
<!ATTLIST table name		ID		#REQUIRED>
<!ATTLIST table space		CDATA		#IMPLIED>

<!ELEMENT column (comment?, size?, default?, check?)>
<!ATTLIST column name		ID		#REQUIRED>
<!ATTLIST column type		CDATA		#REQUIRED>
<!ATTLIST column pkey		(TRUE|FALSE)	"FALSE">
<!ATTLIST column unique		(TRUE|FALSE)	"FALSE">
<!ATTLIST column autoinc	(TRUE|FALSE)	"FALSE">
<!ATTLIST column nnul		(TRUE|FALSE)	"FALSE">

<!ELEMENT comment	(#PCDATA)>
<!ELEMENT size		(#PCDATA)>
<!ELEMENT default	(#PCDATA)>
<!ELEMENT check		(#PCDATA)>

<!ELEMENT fkey (fk_field?)>
<!ATTLIST fkey reftable IDREF 							#IMPLIED>
<!ATTLIST fkey onupdate (RESTRICT|CASCADE|SET_NULL|NO_ACTION|SET_DEFAULT)	#IMPLIED>
<!ATTLIST fkey ondelete (RESTRICT|CASCADE|SET_NULL|NO_ACTION|SET_DEFAULT)	#IMPLIED>

<!ELEMENT fk_field (#PCDATA)>
<!ATTLIST fk_field name	IDREF #REQUIRED>
<!ATTLIST fk_field reffield	IDREF #REQUIRED>

<!ELEMENT view (definition)>
<!ATTLIST view name		ID		#REQUIRED>
<!ATTLIST view replace		(TRUE|FALSE)	"FALSE">
<!ATTLIST view temp		(TRUE|FALSE)	"FALSE">
<!ATTLIST view ifnotexists	(TRUE|FALSE)	"TRUE">

<!ELEMENT definition (#PCDATA)>

=== GNOME/libgda/tests/ddl/ddl-db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "libgda-ddl-creator.dtd">
<schema name="libgda">
  <table name="products" temptable="TRUE">
    <comment>Some comment about table goes here</comment>
    <column name="column_name" type="string" pkey="TRUE" 
            unique="TRUE" autoinc="FALSE" nnul="FALSE">
        <comment>Some column description</comment>
        <size>5</size>
        <default>0</default>
    </column>
    <fkey reftable="products" onupdate="NO_ACTION" ondelete="NO_ACTION">
      <fk_field name="column_name" reffield="column_name"/>
    </fkey>
  </table>
  <view name="MyView" replace="TRUE" temp="FALSE" ifnotexists="TRUE">
    <definition>SELECT * FROM products</definition>
  </view>
</schema>

=== GNOME/libgda/tests/ddl/check_db.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE schema SYSTEM "../../libgda/libgda-ddl-creator.dtd">
<schema>
  <table name="employee">
    <column name="id" type="int" pkey="TRUE"
            unique="TRUE" nnul="TRUE" autoinc="FALSE">
    </column>
    <column name="job_site_id" type="int" nnul="TRUE">
    </column>
    <fkey reftable="job_site">
      <fk_field name="job_site_id" reffield="id"/>
    </fkey>
  </table>
  <table name="job_site">
    <column name="id" type="int" pkey="TRUE"
            unique="TRUE" nnul="TRUE" autoinc="FALSE">
    </column>
    <column name="name" type="string">
      <value size="20"></value>
    </column>
  </table>
</schema>
